blank_issues_enabled: true
contact_links:
  - name: VS Code Marketplace
    url: https://marketplace.visualstudio.com/items?itemName=the-missing-menu
    about: View the extension on VS Code Marketplace